on: workflow_dispatch

env:
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/key4hep:latest

jobs:
  key4hep:
    runs-on: ubuntu-latest
    name: Build key4hep image
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up cvmfs
        uses: cvmfs-contrib/github-action-cvmfs@v3
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up environment
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./key4hep/Dockerfile
          push: true
          tags: ${{ env.LATEST_TAG }}
      - name: Build and push image
        run: | 
          docker run -v /cvmfs/sw.hsf.org:/cvmfs/sw.hsf.org ${{ env.LATEST_TAG }}
          docker commit $(docker ps -aqf "ancestor=${{ env.LATEST_TAG }}") ${{ env.LATEST_TAG }}
          docker image push ${{ env.LATEST_TAG }}
